services:

  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

  weather-db:
    image: postgres:15
    environment:
      POSTGRES_USER: weather_user
      POSTGRES_PASSWORD: weather_password
      POSTGRES_DB: weather

  airflow:
    build: .
    depends_on:
      - airflow-db
      - weather-db
    env_file:
      - .env
    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      PYTHONPATH: /opt/airflow
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./sql:/opt/airflow/sql
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: airflow standalone